apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
        - name: admin-server
          image: pet-store/admin-server:dev
          ports:
            - containerPort: 9000
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
spec:
  type: ClusterIP
  selector:
    app: admin-server
  ports:
    - port: 9000
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: pet-store/product-service:dev
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_BOOT_ADMIN_CLIENT_URL
              value: "http://admin-server:9000"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: pet-store/order-service:dev
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_BOOT_ADMIN_CLIENT_URL
              value: "http://admin-server:9000"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 8082
      targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: makeline-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: makeline-service
  template:
    metadata:
      labels:
        app: makeline-service
    spec:
      containers:
        - name: makeline-service
          image: pet-store/makeline-service:dev
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_BOOT_ADMIN_CLIENT_URL
              value: "http://admin-server:9000"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: makeline-service
spec:
  selector:
    app: makeline-service
  ports:
    - port: 8083
      targetPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-front
  template:
    metadata:
      labels:
        app: store-front
    spec:
      containers:
        - name: store-front
          image: pet-store/store-front:dev
          ports:
            - containerPort: 8080
          env:
            - name: PRODUCT_SERVICE_URL
              value: http://product-service:8081
            - name: ORDER_SERVICE_URL
              value: http://order-service:8082
            - name: SPRING_BOOT_ADMIN_CLIENT_URL
              value: "http://admin-server:9000"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: store-front
spec:
  type: LoadBalancer
  selector:
    app: store-front
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-admin
  template:
    metadata:
      labels:
        app: store-admin
    spec:
      containers:
        - name: store-admin
          image: pet-store/store-admin:dev
          ports:
            - containerPort: 8084
          env:
            - name: PRODUCT_SERVICE_URL
              value: http://product-service:8081
            - name: ORDER_SERVICE_URL
              value: http://order-service:8082
            - name: MAKELINE_SERVICE_URL
              value: http://makeline-service:8083
            - name: SPRING_BOOT_ADMIN_CLIENT_URL
              value: "http://admin-server:9000"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: store-admin
spec:
  type: ClusterIP
  selector:
    app: store-admin
  ports:
    - port: 8084
      targetPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-customer
  template:
    metadata:
      labels:
        app: virtual-customer
    spec:
      containers:
        - name: virtual-customer
          image: pet-store/virtual-customer:dev
          ports:
            - containerPort: 8085
          env:
            - name: PRODUCT_SERVICE_URL
              value: http://product-service:8081
            - name: ORDER_SERVICE_URL
              value: http://order-service:8082
            - name: SPRING_BOOT_ADMIN_CLIENT_URL
              value: "http://admin-server:9000"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-worker
  template:
    metadata:
      labels:
        app: virtual-worker
    spec:
      containers:
        - name: virtual-worker
          image: pet-store/virtual-worker:dev
          ports:
            - containerPort: 8086
          env:
            - name: MAKELINE_SERVICE_URL
              value: http://makeline-service:8083
            - name: SPRING_BOOT_ADMIN_CLIENT_URL
              value: "http://admin-server:9000"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8086
