server:
  port: 8085

spring:
  application:
    name: virtual-customer
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL:http://localhost:9000}
        instance:
          service-base-url: ${SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_BASE_URL:http://localhost:8085}
          prefer-ip: false

simulator:
  customer:
    enabled: ${SIMULATOR_CUSTOMER_ENABLED:true}
    interval-ms: ${SIMULATOR_CUSTOMER_INTERVAL_MS:8000}
    product-service-url: ${PRODUCT_SERVICE_URL:http://localhost:8081}
    order-service-url: ${ORDER_SERVICE_URL:http://localhost:8082}

logging:
  file:
    name: logs/virtual-customer.log

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
