apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pets
resources:
  - ../../base
images:
  - name: pet-store/product-service
    newName: pet-store/product-service
    newTag: dev
  - name: pet-store/order-service
    newName: pet-store/order-service
    newTag: dev
  - name: pet-store/makeline-service
    newName: pet-store/makeline-service
    newTag: dev
  - name: pet-store/store-front
    newName: pet-store/store-front
    newTag: dev
