server:
  port: 8086

spring:
  application:
    name: virtual-worker
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL:http://localhost:9000}
        instance:
          service-base-url: ${SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_BASE_URL:http://localhost:8086}
          prefer-ip: false

simulator:
  worker:
    enabled: ${SIMULATOR_WORKER_ENABLED:true}
    interval-ms: ${SIMULATOR_WORKER_INTERVAL_MS:10000}
    makeline-service-url: ${MAKELINE_SERVICE_URL:http://localhost:8083}

logging:
  file:
    name: logs/virtual-worker.log

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
